#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"

HOST="${HOST:-0.0.0.0}"
PORT="${PORT:-8091}"
LLM_PROVIDER="${LLM_PROVIDER:-ollama}"
OLLAMA_BASE_URL="${OLLAMA_BASE_URL:-${OLLAMA_HOST:-http://localhost:11434}}"
OLLAMA_HOST="$OLLAMA_BASE_URL"
OLLAMA_MODEL="${OLLAMA_MODEL:-qwen3-coder:30b}"
OLLAMA_REQUEST_TIMEOUT_MS="${OLLAMA_REQUEST_TIMEOUT_MS:-600000}"
LLM_CONTEXT_SIZE="${LLM_CONTEXT_SIZE:-${OLLAMA_NUM_CTX:-8192}}"
LLM_TEMPERATURE="${LLM_TEMPERATURE:-0.2}"
LLM_SYSTEM_PROMPT="${LLM_SYSTEM_PROMPT:-}"
OLLAMA_NUM_CTX="$LLM_CONTEXT_SIZE"
OLLAMA_NUM_PREDICT="${OLLAMA_NUM_PREDICT:-512}"
MAX_MODEL_CONTEXT_CHARS="${MAX_MODEL_CONTEXT_CHARS:-24000}"

SSH_USER="${SSH_USER:-tj}"
SSH_KEY="${SSH_KEY:-}"
SSH_BATCH_MODE="${SSH_BATCH_MODE:-1}"
WINDOWS_SSH_USER="${WINDOWS_SSH_USER:-tjing}"
WINDOWS_SSH_KEY="${WINDOWS_SSH_KEY:-$HOME/.ssh/id_ed25519_windows}"
WINDOWS_FILE_ROOT="${WINDOWS_FILE_ROOT:-C:\\Users\\tjing}"
export HOST PORT LLM_PROVIDER OLLAMA_BASE_URL OLLAMA_HOST OLLAMA_MODEL OLLAMA_REQUEST_TIMEOUT_MS LLM_CONTEXT_SIZE LLM_TEMPERATURE LLM_SYSTEM_PROMPT OLLAMA_NUM_CTX OLLAMA_NUM_PREDICT MAX_MODEL_CONTEXT_CHARS SSH_USER SSH_KEY SSH_BATCH_MODE WINDOWS_SSH_USER WINDOWS_SSH_KEY WINDOWS_FILE_ROOT
exec node app.js
