#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"

HOST="${HOST:-0.0.0.0}"
PORT="${PORT:-8091}"
OLLAMA_HOST="${OLLAMA_HOST:-http://100.98.112.1:11434}"
OLLAMA_MODEL="${OLLAMA_MODEL:-qwen2.5-coder:0.5b}"
OLLAMA_REQUEST_TIMEOUT_MS="${OLLAMA_REQUEST_TIMEOUT_MS:-600000}"
OLLAMA_NUM_CTX="${OLLAMA_NUM_CTX:-8192}"
OLLAMA_NUM_PREDICT="${OLLAMA_NUM_PREDICT:-512}"
MAX_MODEL_CONTEXT_CHARS="${MAX_MODEL_CONTEXT_CHARS:-24000}"

SSH_USER="${SSH_USER:-tj}"
export HOST PORT OLLAMA_HOST OLLAMA_MODEL OLLAMA_REQUEST_TIMEOUT_MS OLLAMA_NUM_CTX OLLAMA_NUM_PREDICT MAX_MODEL_CONTEXT_CHARS SSH_USER
exec node app.js
